"""
Offline, deterministic tests for Step 9: script generation orchestration
(shorts/workflow.py's advance()/advance_many(), extended to call the
EXISTING skills.script.write_script_for_workflow one stage past teaching-
approach approval).

No API key, no network — every LLM call here goes through config.STUB exactly
like Steps 3-8.1 (write_script_for_workflow already has a stub path via
Script's existing stub handler).

    python -m shorts.script_orchestration_test
"""
from unittest.mock import patch

from . import config
from .schema import Section, Topic, TopicList, QuestionWorkflow, SectionUnderstanding
from .skills import select, framing as framing_mod, teaching_approach as ta_mod, script as script_mod
from . import review, workflow


def _section(section_id="3.1", title="Why Paging Exists") -> Section:
    text = ("Paging solves external fragmentation by dividing memory into equal "
            "fixed-size frames. Each process is divided into pages of the same "
            "size, and the operating system maintains a page table mapping pages "
            "to frames.")
    return Section(section_id=section_id, title=title, text=text, start_line=1,
                   end_line=5)


def _workflow(topic_id="t_paging", **overrides) -> QuestionWorkflow:
    data = dict(
        id=topic_id, topic="Why does paging remove external fragmentation?",
        why_it_matters="central mechanism", source_section_id="3.1",
        difficulty="medium", importance=5, concept="paging and fragmentation",
        answer_quote="Paging solves external fragmentation by dividing memory "
                     "into equal fixed-size frames.",
    )
    data.update(overrides)
    topic = Topic(**data)
    [selection] = select.build_question_selections(TopicList(topics=[topic]), [_section()])
    return QuestionWorkflow(selection=selection)


def _approved_teaching_approach_workflow(topic_id="t_paging",
                                         section: Section | None = None) -> QuestionWorkflow:
    """Question approved, framed, teaching approach chosen AND approved — no
    script yet. Built WITHOUT going through advance() for the final approval
    step, so a script is never auto-generated by this helper itself; each
    test decides when advance() should run."""
    section = section or _section()
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = review.approve_question(
            _workflow(topic_id, source_section_id=section.section_id))
        wf = workflow.advance(wf, [section]).workflow
        wf = review.approve_teaching_approach(wf)
    finally:
        config.STUB = old_stub
    assert wf.approved_teaching_approach is not None
    assert wf.script is None
    return wf


# --------------------------------------------------------------------------- 1
def test_approved_teaching_approach_triggers_script_generation():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _approved_teaching_approach_workflow()
        result = workflow.advance(wf, [_section()])
    finally:
        config.STUB = old_stub
    assert result.workflow.script is not None
    print("   ok — an approved teaching approach triggers script generation "
          "through advance() (requirement 1)")


# --------------------------------------------------------------------------- 2
def test_generated_script_stored_on_workflow():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _approved_teaching_approach_workflow()
        result = workflow.advance(wf, [_section()])
    finally:
        config.STUB = old_stub
    from .schema import Script
    assert isinstance(result.workflow.script, Script)
    assert result.workflow.script.question
    print("   ok — the generated script is stored in QuestionWorkflow.script "
          "(requirement 2)")


# --------------------------------------------------------------------------- 3
def test_status_becomes_ready_for_visual_planning():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _approved_teaching_approach_workflow()
        result = workflow.advance(wf, [_section()])
    finally:
        config.STUB = old_stub
    assert result.status == "awaiting_visual_plan_approval"
    print("   ok — status becomes ready_for_visual_planning once a script "
          "exists (requirement 3)")


# --------------------------------------------------------------------------- 4
def test_pending_question_does_not_generate_script():
    wf = _workflow()
    with patch.object(script_mod, "ask_json", side_effect=AssertionError(
            "must not write a script for a pending question")):
        result = workflow.advance(wf, [_section()])
    assert result.status == "awaiting_question_approval"
    assert result.workflow.script is None
    print("   ok — a pending question does not generate a script "
          "(requirement 4)")


# --------------------------------------------------------------------------- 5
def test_rejected_question_does_not_generate_script():
    wf = review.reject_question(_workflow(), note="not needed")
    with patch.object(script_mod, "ask_json", side_effect=AssertionError(
            "must not write a script for a rejected question")):
        result = workflow.advance(wf, [_section()])
    assert result.status == "rejected"
    assert result.workflow.script is None
    print("   ok — a rejected question does not generate a script "
          "(requirement 5)")


# --------------------------------------------------------------------------- 6
def test_missing_framing_does_not_skip_straight_to_script():
    # An inconsistent hand-built state (approved teaching approach, but no
    # framing) — advance() must still regenerate FRAMING first, never jump
    # ahead to script generation with a missing precondition.
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _approved_teaching_approach_workflow()
        broken = wf.model_copy(update={"framing": None})
        with patch.object(script_mod, "ask_json", side_effect=AssertionError(
                "must not write a script while framing is missing")):
            result = workflow.advance(broken, [_section()])
    finally:
        config.STUB = old_stub
    # advance() self-heals framing (its own idempotency contract: None means
    # not yet decided) rather than crashing or skipping ahead.
    assert result.workflow.framing is not None
    assert result.workflow.script is None
    print("   ok — missing framing is regenerated, never skipped past, so no "
          "script is written on top of it in the same call (requirement 6)")


# --------------------------------------------------------------------------- 7
def test_pending_teaching_approach_approval_does_not_generate_script():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = review.approve_question(_workflow())
        wf = workflow.advance(wf, [_section()]).workflow   # framed + chosen, not approved
        assert wf.teaching_approach_approval.status == "pending"
        with patch.object(script_mod, "ask_json", side_effect=AssertionError(
                "must not write a script before teaching-approach approval")):
            result = workflow.advance(wf, [_section()])
    finally:
        config.STUB = old_stub
    assert result.status == "awaiting_teaching_approach_approval"
    assert result.workflow.script is None
    print("   ok — a pending teaching-approach approval does not generate a "
          "script (requirement 7)")


# --------------------------------------------------------------------------- 8
def test_repeated_advance_after_script_does_not_call_llm_again():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _approved_teaching_approach_workflow()
        first = workflow.advance(wf, [_section()]).workflow
        with patch.object(script_mod, "ask_json", side_effect=AssertionError(
                "script must not be regenerated on a second advance() call")):
            again = workflow.advance(first, [_section()])
    finally:
        config.STUB = old_stub
    assert again.status == "awaiting_visual_plan_approval"
    assert again.workflow.script == first.script
    print("   ok — a second advance() call after script generation makes no "
          "further LLM call (requirement 8)")


# --------------------------------------------------------------------------- 9
def test_advance_many_generates_scripts_only_for_eligible_workflows():
    section = _section()
    old_stub = config.STUB
    config.STUB = True
    try:
        pending = _workflow(topic_id="t_pending")
        approved_q_only = review.approve_question(_workflow(topic_id="t_approved_q"))
        ready_for_script = _approved_teaching_approach_workflow(topic_id="t_ready")

        results = workflow.advance_many(
            [pending, approved_q_only, ready_for_script], [section])
    finally:
        config.STUB = old_stub

    by_id = {r.workflow.selection.topic.id: r for r in results}
    assert by_id["t_pending"].status == "awaiting_question_approval"
    assert by_id["t_pending"].workflow.script is None
    assert by_id["t_approved_q"].status == "awaiting_teaching_approach_approval"
    assert by_id["t_approved_q"].workflow.script is None
    assert by_id["t_ready"].status == "awaiting_visual_plan_approval"
    assert by_id["t_ready"].workflow.script is not None
    print("   ok — advance_many generates scripts only for workflows that "
          "actually reached the script stage (requirement 9)")


# -------------------------------------------------------------------------- 10
def test_understanding_reused_for_script_generation():
    # PATCH THE NAME AS shorts.workflow ITSELF SEES IT, not
    # skills.script.write_script_for_workflow — workflow.py did
    # `from .skills.script import write_script_for_workflow`, which binds a
    # SEPARATE reference into workflow's own namespace at import time;
    # patching the original module's attribute would not touch that binding.
    captured = {}
    real_write_script_for_workflow = workflow.write_script_for_workflow

    def spy(wf, section, **kw):
        captured["understanding"] = kw.get("understanding")
        return real_write_script_for_workflow(wf, section, **kw)

    old_stub = config.STUB
    config.STUB = True
    workflow.write_script_for_workflow = spy
    try:
        wf = _approved_teaching_approach_workflow()
        u = SectionUnderstanding(section_id="3.1",
                                 core_idea="paging removes external fragmentation")
        workflow.advance(wf, [_section()], understanding=u)
    finally:
        workflow.write_script_for_workflow = real_write_script_for_workflow
        config.STUB = old_stub

    assert captured["understanding"] is u
    print("   ok — advance() passes the SAME SectionUnderstanding object to "
          "script generation as it would to framing/teaching-approach "
          "(requirement 10)")


def test_advance_many_fetches_understanding_for_a_workflow_at_the_script_stage():
    # A HUMAN GATE ALWAYS SITS BETWEEN teaching-approach generation and
    # script generation (teaching_approach_approval must be explicitly
    # "approved" — nothing here can skip that), so a single advance_many
    # call can never carry a workflow from "just approved" all the way to
    # "scripted": that would require auto-approving the teaching approach,
    # which this module must never do. This test instead confirms the
    # SCRIPT stage's OWN understanding fetch fires correctly when IT is the
    # only remaining stage — the realistic shape of a second advance_many
    # call, made after a human has approved the teaching approach.
    calls = {"n": 0}
    from shorts.skills import understanding as u_mod
    real_understand = u_mod.understand

    def counting(*a, **kw):
        calls["n"] += 1
        return real_understand(*a, **kw)

    old_stub = config.STUB
    config.STUB = True
    u_mod.understand = counting
    try:
        section = Section(section_id="9.9", title="A section only this test uses",
                          text="A cache-isolation fixture unique to this test, so "
                              "understanding_for cannot have already cached it.",
                          start_line=1, end_line=1)
        wf = _approved_teaching_approach_workflow(topic_id="t_script_stage",
                                                  section=section)
        results = workflow.advance_many([wf], [section])
    finally:
        u_mod.understand = real_understand
        config.STUB = old_stub
    assert results[0].status == "awaiting_visual_plan_approval"
    assert calls["n"] == 1, (
        f"expected exactly one understanding call for the script stage, "
        f"got {calls['n']}")
    print("   ok — advance_many fetches understanding for a workflow that "
          "has reached the script stage alone (requirement 10)")


def test_understanding_cache_carries_across_separate_advance_many_calls():
    # THE REALISTIC CROSS-STAGE STORY, given the human gate above: the FIRST
    # advance_many call (framing + teaching-approach, stops at the gate) and
    # the SECOND one (made later, after a human approves — script alone)
    # are two SEPARATE calls. They still end up sharing one reading, because
    # skills.understanding.understanding_for's own process-wide cache (keyed
    # by section text) makes the second call's fetch a cache hit — no
    # feature Step 9 had to add, just existing infrastructure this
    # orchestration correctly does not bypass.
    calls = {"n": 0}
    from shorts.skills import understanding as u_mod
    real_understand = u_mod.understand

    def counting(*a, **kw):
        calls["n"] += 1
        return real_understand(*a, **kw)

    old_stub = config.STUB
    config.STUB = True
    u_mod.understand = counting
    try:
        section = Section(section_id="9.7", title="A third section unique to this test",
                          text="A third cache-isolation fixture, unique to this "
                              "specific test function's own section id.",
                          start_line=1, end_line=1)
        wf = review.approve_question(_workflow(topic_id="t_cache", source_section_id="9.7"))
        first = workflow.advance_many([wf], [section])[0]
        assert first.status == "awaiting_teaching_approach_approval"
        assert calls["n"] == 1

        wf2 = review.approve_teaching_approach(first.workflow)
        second = workflow.advance_many([wf2], [section])[0]
    finally:
        u_mod.understand = real_understand
        config.STUB = old_stub
    assert second.status == "awaiting_visual_plan_approval"
    assert calls["n"] == 1, (
        f"expected the second advance_many call to hit understanding_for's "
        f"own cache (still 1 total understand() call), got {calls['n']}")
    print("   ok — a later advance_many call for the script stage reuses "
          "the cached reading from the earlier framing/teaching-approach "
          "call, rather than fetching a second time (requirement 10)")


# -------------------------------------------------------------------------- 11
def test_at_most_one_understanding_fetch_per_section_across_multiple_workflows():
    calls = {"n": 0}
    from shorts.skills import understanding as u_mod
    real_understand = u_mod.understand

    def counting(*a, **kw):
        calls["n"] += 1
        return real_understand(*a, **kw)

    old_stub = config.STUB
    config.STUB = True
    u_mod.understand = counting
    try:
        section = Section(section_id="9.8", title="Another section unique to this test",
                          text="Another cache-isolation fixture unique to this "
                              "specific test function.",
                          start_line=1, end_line=1)
        wf_a = review.approve_question(_workflow(topic_id="t_a2", source_section_id="9.8"))
        wf_b = review.approve_question(_workflow(topic_id="t_b2", source_section_id="9.8"))
        results = workflow.advance_many([wf_a, wf_b], [section])
    finally:
        u_mod.understand = real_understand
        config.STUB = old_stub
    assert all(r.status == "awaiting_teaching_approach_approval" for r in results)
    assert calls["n"] == 1, (
        f"expected exactly one understanding call shared by both workflows, "
        f"got {calls['n']}")
    print("   ok — at most one understanding fetch occurs per section across "
          "multiple workflows in one advance_many call (requirement 11)")


# -------------------------------------------------------------------------- 12
def test_question_regeneration_clears_script_and_blocks_generation():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _approved_teaching_approach_workflow()
        wf = workflow.advance(wf, [_section()]).workflow
        assert wf.script is not None

        wf2 = review.regenerate(wf, "too broad, focus on the mechanism", [_section()])
        assert wf2.script is None
        with patch.object(script_mod, "ask_json", side_effect=AssertionError(
                "must not write a script before the regenerated question is "
                "approved")):
            result = workflow.advance(wf2, [_section()])
    finally:
        config.STUB = old_stub
    assert result.status == "awaiting_question_approval"
    assert result.workflow.script is None
    print("   ok — question regeneration clears script and blocks generation "
          "until re-approval (requirement 12)")


# -------------------------------------------------------------------------- 13
def test_fresh_script_after_regenerated_question_reapproved():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _approved_teaching_approach_workflow()
        wf = workflow.advance(wf, [_section()]).workflow
        original_script = wf.script

        wf2 = review.regenerate(wf, "too broad, focus on the mechanism", [_section()])
        wf2 = review.approve_question(wf2)
        wf2 = workflow.advance(wf2, [_section()]).workflow   # fresh framing + approach
        wf2 = review.approve_teaching_approach(wf2)
        result = workflow.advance(wf2, [_section()])
    finally:
        config.STUB = old_stub
    assert result.status == "awaiting_visual_plan_approval"
    assert result.workflow.script is not None
    assert result.workflow.script.question == result.workflow.framing.teaching_question
    assert result.workflow.script.question != original_script.question
    print("   ok — advance() generates a fresh script after the regenerated "
          "question is re-approved through the whole chain (requirement 13)")


# -------------------------------------------------------------------------- 14
def test_teaching_approach_regeneration_clears_script():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _approved_teaching_approach_workflow()
        wf = workflow.advance(wf, [_section()]).workflow
        assert wf.script is not None

        wf2 = review.regenerate_teaching_approach(wf, "code is not necessary",
                                                   [_section()])
    finally:
        config.STUB = old_stub
    assert wf2.script is None
    print("   ok — teaching-approach regeneration clears script "
          "(requirement 14)")


# -------------------------------------------------------------------------- 15
def test_fresh_script_after_regenerated_approach_reapproved():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _approved_teaching_approach_workflow()
        wf = workflow.advance(wf, [_section()]).workflow
        original_script = wf.script

        wf2 = review.regenerate_teaching_approach(wf, "code is not necessary",
                                                   [_section()])
        assert wf2.script is None
        with patch.object(script_mod, "ask_json", side_effect=AssertionError(
                "must not write a script before the regenerated approach is "
                "approved")):
            blocked = workflow.advance(wf2, [_section()])
        assert blocked.status == "awaiting_teaching_approach_approval"

        wf2 = review.approve_teaching_approach(wf2)
        result = workflow.advance(wf2, [_section()])
    finally:
        config.STUB = old_stub
    assert result.status == "awaiting_visual_plan_approval"
    assert result.workflow.script is not None
    print("   ok — advance() generates a fresh script after a regenerated "
          "teaching approach is re-approved (requirement 15)")


# -------------------------------------------------------------------------- 16
def test_existing_framing_and_teaching_approach_orchestration_unchanged():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = review.approve_question(_workflow())
        result = workflow.advance(wf, [_section()])
    finally:
        config.STUB = old_stub
    # Exactly Step 7's own behavior: one advance() call on a freshly-approved
    # question produces both framing and a teaching approach and stops at
    # the teaching-approach gate — script generation does not fire yet.
    assert result.status == "awaiting_teaching_approach_approval"
    assert result.workflow.framing is not None
    assert result.workflow.teaching_approach is not None
    assert result.workflow.script is None
    print("   ok — framing/teaching-approach orchestration behavior is "
          "unchanged by Step 9 (requirement 16)")


# -------------------------------------------------------------------------- 17
def test_existing_topic_based_script_generation_unchanged():
    from .skills.script import write_script
    section = _section()
    topic = Topic(id="t1", topic="Why does paging remove external fragmentation?",
                 why_it_matters="m", source_section_id="3.1", difficulty="medium")
    old_stub = config.STUB
    config.STUB = True
    try:
        sc = write_script(topic, section)
    finally:
        config.STUB = old_stub
    assert sc.question == topic.topic
    print("   ok — plain Topic-based write_script is unaffected by Step 9 "
          "orchestration (requirement 17)")


# -------------------------------------------------------------------------- 18
def test_stub_mode_executes_complete_workflow_through_script_generation():
    old_stub = config.STUB
    config.STUB = True
    try:
        wf = _workflow()
        wf = review.approve_question(wf)
        result = workflow.advance(wf, [_section()])
        assert result.status == "awaiting_teaching_approach_approval"

        wf = review.approve_teaching_approach(result.workflow)
        result = workflow.advance(wf, [_section()])
    finally:
        config.STUB = old_stub
    assert result.status == "awaiting_visual_plan_approval"
    assert result.workflow.script is not None
    assert result.workflow.approved_topic is not None
    assert result.workflow.approved_teaching_approach is not None
    print("   ok — stub mode executes the complete workflow, selection "
          "through script generation (requirement 18)")


def main():
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    print(f"running {len(tests)} script-orchestration (Step 9) tests")
    for t in tests:
        print(f"- {t.__name__}")
        t()
    print("\nALL SCRIPT ORCHESTRATION TESTS PASSED.")


if __name__ == "__main__":
    main()
