"""
RESTYLE_TO_STORY_REELS.md Step 5: unit tests for skills.visuals.build_shot_prompt
(+ its helpers) and shorts/story_frames.py.

No API key, no network, no real provider calls — every test runs under
SHORTS_STUB=1 against output/stub_e2e.story.json (regenerated by
story_mode_test.py's own end-to-end test), and refs/setting-ref/cache
behavior is checked with a fake ImageProvider, not a real one.

    SHORTS_STUB=1 python -m shorts.story_frames_test
"""
import os
if os.environ.get("SHORTS_STUB", "").strip().lower() not in ("1", "true", "yes"):
    raise SystemExit("run this with SHORTS_STUB=1 — it never spends real API calls")

import contextlib
import io
import json
import re
import shutil
from pathlib import Path

from shorts import cast_sheets, config, frame_checks, imagegen, story_frames
from shorts.imagegen import ImageGenError
from shorts.schema import Shot, StoryFrameJudge
from shorts.skills.visuals import allowed_glyphs, build_shot_prompt, cast_refs_for_shot


STORY_PATH = config.OUTPUT_DIR / "stub_e2e.story.json"


def _ensure_stub_story():
    """
    output/stub_e2e.story.json is written by story_mode_test.py's own
    test_full_story_path_runs_end_to_end_under_stub. Generate it here too
    (idempotent, free under SHORTS_STUB=1) so this file can run standalone
    without depending on test execution order across files.
    """
    if STORY_PATH.exists():
        return
    import shorts.story_mode_test as smt
    smt.test_full_story_path_runs_end_to_end_under_stub()


def _load_story():
    from shorts.schema import StoryScript
    return StoryScript.model_validate_json(STORY_PATH.read_text(encoding="utf-8"))


def _approve_full_cast():
    shutil.rmtree(cast_sheets.ASSETS_DIR, ignore_errors=True)
    shutil.rmtree(cast_sheets.CANDIDATES_DIR, ignore_errors=True)
    for name in cast_sheets.CAST_ORDER:
        cast_sheets.main(["--candidates", "1", "--character", name.lower(), "--yes"])
        cast_sheets.main(["--approve", name.lower(), "1"])


def _clean_reel_output(short_id: str):
    shutil.rmtree(config.OUTPUT_DIR / short_id, ignore_errors=True)
    imagegen.reset_call_count(short_id)


def _dedicated_short_id(short_id: str) -> None:
    """
    story_frames.main() reads output/<short_id>.story.json, keyed by the
    exact short_id argv[0] — a test that wants its OWN output directory
    (rather than sharing "stub_e2e" with every other test in this file)
    needs a matching story file under that name too, not just a clean
    output dir. Copies the shared stub story once under the new name.
    """
    _clean_reel_output(short_id)
    dst = config.OUTPUT_DIR / f"{short_id}.story.json"
    if not dst.exists():
        dst.write_text(STORY_PATH.read_text(encoding="utf-8"), encoding="utf-8")


def _run(argv):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        code = story_frames.main(argv)
    return code, buf.getvalue()


# Every shot's prompt is DETERMINISTIC (see test_build_shot_prompt_is_
# deterministic below) — the same fixed stub story, run twice, asks for the
# exact same prompts every time. That's the point (it's what makes a real
# provider's cache work at all), but it means output/.image_cache/ from a
# PREVIOUS run of this exact file would make every "was the provider called"
# check below a false negative on run 2 onward. Cleared once, here, so this
# file's own monkeypatched-call-counting tests start from a clean cache
# regardless of what an earlier run left behind — the cache itself is
# disposable, regenerable content, never anything worth preserving.
shutil.rmtree(config.OUTPUT_DIR / ".image_cache", ignore_errors=True)

_ensure_stub_story()
_approve_full_cast()


# ============================================================ allowed_glyphs

def test_allowed_glyphs_extracts_isolated_single_digits():
    shot = Shot(shot_id="x", action="the button reads 0 after the click",
               key_prop="button")
    assert allowed_glyphs(shot) == "0"
    print("   ok — a single, isolated digit essential to the action is allowed")


def test_allowed_glyphs_excludes_multi_digit_numbers():
    shot = Shot(shot_id="x", action="the counter now shows 15 on its face")
    assert allowed_glyphs(shot) == "", allowed_glyphs(shot)
    print("   ok — a multi-digit number (each digit has a digit neighbour) is "
          "never an allowed glyph")


def test_allowed_glyphs_never_words_or_code():
    shot = Shot(shot_id="x", action='Rahul stares at the const count = 0 line',
               key_prop="notebook")
    glyphs = allowed_glyphs(shot)
    assert "const" not in glyphs and "count" not in glyphs
    assert glyphs == "0"
    print(f"   ok — only the isolated digit is extracted, never the "
          f"surrounding words/code: {glyphs!r}")


def test_allowed_glyphs_none_when_no_digit():
    shot = Shot(shot_id="x", action="Rahul stares at the blank whiteboard")
    assert allowed_glyphs(shot) == ""
    print("   ok — no digits in the shot at all -> empty (rendered as 'none' "
          "by build_shot_prompt)")


# ========================================================== build_shot_prompt

def test_build_shot_prompt_is_deterministic():
    story = _load_story()
    shot = next(s for s in story.shots if s.kind == "scene" and s.characters)
    p1 = build_shot_prompt(shot, story)
    p2 = build_shot_prompt(shot, story)
    assert p1 == p2
    print("   ok — the same shot + story always produces the identical "
          "prompt string (what makes repeat calls a cache hit)")


def test_build_shot_prompt_contains_every_required_section():
    story = _load_story()
    shot = next(s for s in story.shots if s.kind == "scene" and s.key_prop)
    prompt = build_shot_prompt(shot, story)
    for marker in ("STYLE_BIBLE" if False else "Hand-drawn stick figure",
                  f"SETTING: {story.setting}", "SHOT:", "EMOTION:", "ACTION:",
                  "KEY OBJECT (glowing softly yellow):", "ALLOWED GLYPHS:"):
        assert marker in prompt, marker
    print("   ok — every required section (style bible, setting, shot, per-"
          "character look+ref, emotion, action, key object, glyphs) is present")


def test_build_shot_prompt_no_text_card_recap_cta_shape():
    """text_card/recap/cta shots are never passed to build_shot_prompt by
    story_frames.py (they're filtered out before rendering) — this just
    confirms the filter, not build_shot_prompt itself refusing them."""
    story = _load_story()
    non_scene = [s for s in story.shots if s.kind != "scene"]
    assert non_scene, "the stub story should have text_card/recap/cta shots"
    scene_ids = {s.shot_id for s in story_frames._scene_shots(story)}
    assert not any(s.shot_id in scene_ids for s in non_scene)
    print(f"   ok — story_frames._scene_shots excludes every non-scene shot: "
         f"{[s.kind for s in non_scene]}")


def test_build_shot_prompt_avoids_full_bodies_for_a_character_less_shot():
    """
    STEP 9 FIXES ROUND 10: a real run hit repeated image-generation
    failures on shot 1 (the hook — `characters` always empty per its own
    STRUCTURE rule, "wide" framing) — one content-policy refusal (NSFW
    code 8007) and two empty responses, all on the identical prompt. That
    prompt said "full bodies, room visible" while the shot's own `action`
    described an EMPTY room with nobody in it — a self-contradictory
    instruction (asking for bodies that don't exist) that is a plausible
    trigger for a miscalibrated safety filter, not just bad luck.
    Confirms a character-less shot's prompt no longer claims "full
    bodies" and instead states there are no people in frame."""
    story = _load_story()
    shot = next(s for s in story.shots if s.kind == "scene" and not s.characters)
    prompt = build_shot_prompt(shot, story)
    assert "full bodies" not in prompt
    assert "no people in frame" in prompt
    shot_line = next(l for l in prompt.splitlines() if l.startswith("SHOT:"))
    print(f"   ok — a character-less shot's prompt no longer says 'full "
         f"bodies' (nothing to anchor it to): {shot_line!r}")


def test_build_shot_prompt_still_says_full_bodies_for_a_wide_shot_with_characters():
    """Regression guard: only the character-LESS case changed — a wide
    shot that actually has characters in it must keep saying 'full
    bodies, room visible', unchanged."""
    story = _load_story()
    shot = next(s for s in story.shots
               if s.kind == "scene" and s.characters and s.framing == "wide")
    prompt = build_shot_prompt(shot, story)
    assert "full bodies, room visible" in prompt
    print("   ok — a wide shot WITH characters still says 'full bodies, room "
         "visible', unchanged")


def test_build_shot_prompt_no_people_in_frame_for_every_character_less_framing():
    """The self-contradiction isn't unique to 'wide' — a character-less
    shot framed close_up or two_shot ("head and shoulders" / "two
    characters facing each other" with zero characters) is exactly as
    broken. Confirms all three framings are covered for the no-characters
    case, not just the one the real run happened to hit."""
    story = _load_story()
    for framing in ("wide", "close_up", "two_shot"):
        shot = Shot(shot_id="x", characters=[], action="an empty room",
                   kind="scene", framing=framing)
        prompt = build_shot_prompt(shot, story)
        assert "full bodies" not in prompt, framing
        assert "head and shoulders" not in prompt, framing
        assert "two characters facing each other" not in prompt, framing
        assert "no people in frame" in prompt, framing
    print("   ok — every framing (wide/close_up/two_shot) avoids implying "
         "characters that don't exist when the shot's own `characters` is "
         "empty")


# ============================================================ cast_refs_for_shot

def test_cast_refs_for_shot_missing_sheet_raises_clear_error():
    shutil.rmtree(cast_sheets.ASSETS_DIR, ignore_errors=True)
    shot = Shot(shot_id="s99", characters=["Rahul", "System"], action="a")
    try:
        cast_refs_for_shot(shot)
        assert False, "expected ImageGenError"
    except ImageGenError as e:
        assert "s99" in str(e) and "Rahul" in str(e) and "System" in str(e)
        print(f"   ok — a shot with no approved cast sheets at all raises, "
             f"naming every missing character and the shot_id: {e}")
    finally:
        _approve_full_cast()


def test_cast_refs_for_shot_order_matches_characters_order():
    _approve_full_cast()
    shot = Shot(shot_id="s0", characters=["Rahul", "System"], action="a")
    refs = cast_refs_for_shot(shot)
    assert [r.stem for r in refs] == ["rahul", "system"]
    print(f"   ok — refs come back in the shot's own characters order: "
         f"{[r.name for r in refs]}")


# =================================================================== --dry-run

def test_dry_run_writes_prompts_and_calls_no_provider():
    _clean_reel_output("stub_e2e")
    calls = []
    original = imagegen.StubImageProvider.generate
    imagegen.StubImageProvider.generate = lambda self, *a, **kw: (calls.append(1), original(self, *a, **kw))[1]
    try:
        code, out = _run(["stub_e2e", "--dry-run"])
    finally:
        imagegen.StubImageProvider.generate = original

    assert code == 0
    assert not calls, "dry-run must never call a provider"
    prompts_path = config.OUTPUT_DIR / "stub_e2e" / "image_prompts.json"
    assert prompts_path.exists()
    entries = json.loads(prompts_path.read_text())
    assert len(entries) > 0
    frames_dir = config.OUTPUT_DIR / "stub_e2e" / "frames"
    assert not frames_dir.exists() or not list(frames_dir.glob("*.png"))
    print(f"   ok — --dry-run writes {len(entries)} prompt(s) to {prompts_path} "
         f"and renders zero frames")


def test_dry_run_skips_text_card_and_recap_shots():
    _clean_reel_output("stub_e2e")
    story = _load_story()
    _run(["stub_e2e", "--dry-run"])
    entries = json.loads((config.OUTPUT_DIR / "stub_e2e" / "image_prompts.json").read_text())
    shot_ids = {e["shot_id"] for e in entries}
    skipped_kinds = {s.kind for s in story.shots if s.shot_id in shot_ids} - {"scene", "cta"}
    assert not skipped_kinds, skipped_kinds
    text_card_and_recap_ids = {s.shot_id for s in story.shots if s.kind in ("text_card", "recap")}
    assert not (shot_ids & text_card_and_recap_ids)
    print("   ok — text_card and recap shots never appear in image_prompts.json "
          "(only scene shots + the cta/mascot entry do)")


def test_mascot_prompt_built_once_and_cache_reused_across_reels():
    """
    The cta entry's prompt is style.mascot_prompt() — identical text
    regardless of reel — so a second reel's cta call is a cache hit, not a
    second real call.

    Checks "reel_b triggers NO ADDITIONAL provider call beyond whatever
    reel_a triggered" rather than "exactly 1 call total" — output/.image_cache/
    persists on disk across test runs (by design: that's the whole point of
    a cache), so a prior run of this exact test may have already cached
    mascot_prompt()'s image, making reel_a ITSELF a hit too (0 calls, not 1).
    Either way, the invariant that actually matters — reel_b never adds a
    2nd real call on top of reel_a's — holds regardless of that history.
    """
    from shorts import style
    calls = []
    original = imagegen.StubImageProvider.generate
    imagegen.StubImageProvider.generate = lambda self, *a, **kw: (calls.append(1), original(self, *a, **kw))[1]
    try:
        imagegen.generate_bytes("reel_a", "cta", style.mascot_prompt(),
                               provider=imagegen.StubImageProvider())
        after_a = len(calls)
        imagegen.generate_bytes("reel_b", "cta", style.mascot_prompt(),
                               provider=imagegen.StubImageProvider())
        after_b = len(calls)
    finally:
        imagegen.StubImageProvider.generate = original
    assert after_a <= 1 and after_b == after_a, (after_a, after_b)
    print(f"   ok — two different reels' cta calls, same mascot prompt, "
         f"share one cache entry — reel_b added zero additional real calls "
         f"(calls so far: {after_a})")


# ========================================================== refs + setting ref

class _RecordingProvider(imagegen.StubImageProvider):
    """Records the refs list every generate() call received, so a test can
    check ordering/setting-ref-augmentation without inspecting pixels.

    OWN `name`, distinct from "stub" — the cache key is sha256(provider.name
    + model + prompt + ...), so sharing StubImageProvider's plain "stub" name
    would let a cache entry written by any OTHER test's plain StubImageProvider
    (identical prompt+refs+seed) silently serve this one from cache, and
    generate() would never be called at all — nothing to record, and a false
    pass/fail depending on test execution order and leftover .image_cache/
    state from earlier runs."""
    name = "stub_recording"

    def __init__(self):
        self.calls = []

    def generate(self, prompt, refs=None, size=imagegen.FRAME_SIZE, seed=None, shot_id=""):
        self.calls.append({"shot_id": shot_id, "refs": list(refs or [])})
        return super().generate(prompt, refs=refs, size=size, seed=seed, shot_id=shot_id)


def test_refs_order_matches_reference_image_n_in_the_prompt():
    _clean_reel_output("stub_e2e_refs")
    story = _load_story()
    two_char_shot = next(s for s in story.shots if s.kind == "scene" and len(s.characters) == 2)
    prompt = build_shot_prompt(two_char_shot, story)

    # Parse "reference image N" against each named character, in the order
    # the PROMPT names them (not shot.characters — the prompt is the
    # contract a real provider actually reads).
    named_in_order = re.findall(r"^(\w+): .*matching reference image (\d+)", prompt, re.M)
    assert [n for n, _ in named_in_order] == two_char_shot.characters
    assert [i for _, i in named_in_order] == ["1", "2"]

    provider = _RecordingProvider()
    refs = cast_refs_for_shot(two_char_shot)
    imagegen.generate_bytes("stub_e2e_refs", two_char_shot.shot_id, prompt,
                            refs=refs, provider=provider)
    got_refs = provider.calls[0]["refs"]
    assert [r.stem for r in got_refs] == [c.lower() for c in two_char_shot.characters]
    print(f"   ok — the prompt's 'reference image 1/2' order "
         f"({[n for n, _ in named_in_order]}) matches the refs list actually "
         f"passed to the provider ({[r.name for r in got_refs]})")


def test_first_wide_frame_becomes_setting_ref_for_later_shots():
    """
    Drives the SAME logic story_frames.run() uses (render the first wide
    shot, then pass its path as an extra ref to every later shot) directly
    against a _RecordingProvider, so the refs each call actually received
    can be inspected — run() itself always asks imagegen.select_provider()
    for a fresh provider internally, which would hide that from a test
    calling run() as a black box.
    """
    _clean_reel_output("stub_e2e_setting")
    story = _load_story()
    provider = _RecordingProvider()
    shots = story_frames.select_sample(story_frames._scene_shots(story), 3)

    wide = next(s for s in shots if s.framing == "wide")
    others = [s for s in shots if s.shot_id != wide.shot_id]
    wide_path = imagegen.render_frame("stub_e2e_setting", wide.shot_id,
                                      build_shot_prompt(wide, story),
                                      refs=cast_refs_for_shot(wide), provider=provider)
    for s in others:
        refs = cast_refs_for_shot(s) + [wide_path]
        imagegen.generate_bytes("stub_e2e_setting", s.shot_id, build_shot_prompt(s, story),
                                refs=refs, provider=provider)

    later_calls = [c for c in provider.calls if c["shot_id"] != wide.shot_id]
    assert later_calls, "need at least one non-wide shot in the sample to check this"
    for c in later_calls:
        assert wide_path in c["refs"], (c["shot_id"], c["refs"])
    print(f"   ok — every shot after the first wide one carries {wide_path.name} "
         f"as an extra (setting) reference")


# =============================================================== --sample N

def test_sample_selection_covers_wide_close_up_two_shot_and_all_cast():
    story = _load_story()
    scene_shots = story_frames._scene_shots(story)
    sample = story_frames.select_sample(scene_shots, 5)

    framings = {s.framing for s in sample}
    assert {"wide", "close_up", "two_shot"} <= framings, framings

    all_cast = {c for s in scene_shots for c in s.characters}
    sampled_cast = {c for s in sample for c in s.characters}
    assert all_cast <= sampled_cast, (all_cast, sampled_cast)

    first_wide = next(s for s in scene_shots if s.framing == "wide")
    assert sample[0].shot_id == first_wide.shot_id
    print(f"   ok — --sample 5 ({[s.shot_id for s in sample]}) covers every "
         f"framing {framings} and every cast member {sampled_cast}, starting "
         f"with the first wide shot")


def test_sample_grows_past_n_when_guarantees_need_it():
    """If N is too small to fit every guarantee, the guarantees win — more
    than N shots come back rather than silently dropping one."""
    story = _load_story()
    scene_shots = story_frames._scene_shots(story)
    sample = story_frames.select_sample(scene_shots, 1)
    framings = {s.framing for s in sample}
    assert {"wide", "close_up", "two_shot"} <= framings
    assert len(sample) > 1
    print(f"   ok — --sample 1 still returns {len(sample)} shots because the "
         f"framing/cast guarantees need more than 1")


# ==================================================================== --all

def test_all_selects_every_scene_shot_only():
    story = _load_story()
    scene_shots = story_frames._scene_shots(story)
    code, out = _run(["stub_e2e", "--all", "--dry-run"])
    entries = json.loads((config.OUTPUT_DIR / "stub_e2e" / "image_prompts.json").read_text())
    scene_and_cta_ids = {s.shot_id for s in scene_shots} | {
        s.shot_id for s in story.shots if s.kind == "cta"}
    assert {e["shot_id"] for e in entries} == scene_and_cta_ids
    print(f"   ok — --all renders every scene shot ({len(scene_shots)}) plus "
         f"the mascot/cta entry, nothing else")


# ============================================================ cost + --yes gate

def test_estimate_printed_and_yes_required():
    _clean_reel_output("stub_e2e")
    calls = []
    original = imagegen.StubImageProvider.generate
    imagegen.StubImageProvider.generate = lambda self, *a, **kw: (calls.append(1), original(self, *a, **kw))[1]
    try:
        code, out = _run(["stub_e2e", "--sample", "5"])
    finally:
        imagegen.StubImageProvider.generate = original

    assert code != 0
    assert not calls
    assert "Estimated cost" in out
    assert "Planned calls" in out
    frames_dir = config.OUTPUT_DIR / "stub_e2e" / "frames"
    assert not frames_dir.exists() or not list(frames_dir.glob("*.png"))
    print(f"   ok — cost estimate is printed and no frame is rendered "
         f"without --yes: {[l for l in out.splitlines() if 'cost' in l.lower()]}")


# ============================================ STEP 7 Part 0 #1 — image budget

def test_default_image_budget_formula():
    assert config.default_image_budget(5, 2, has_mascot=True) == 5 * 2 + 1 + config.IMAGE_CALLS_HEADROOM
    assert config.default_image_budget(5, 2, has_mascot=False) == 5 * 2 + config.IMAGE_CALLS_HEADROOM
    print(f"   ok — default_image_budget is (shots x attempts) + mascot + "
         f"headroom ({config.IMAGE_CALLS_HEADROOM}): "
         f"{config.default_image_budget(5, 2, has_mascot=True)}")


def test_story_frame_judge_preflight_cost_is_no_longer_a_silent_zero():
    """
    STEP 9 FIXES ROUND 14: a real sample stage showed $0.0000 estimated but
    $0.0430 actual cost for story_frame_judge (gemini-3.8-flash) — two
    compounding bugs, both fixed: (1) usage.PRICES had no entry for this
    model at all (config.py's old note wrongly assumed it was genuinely
    free — it goes through OpenRouter, which bills real money regardless of
    Google's own free tier), and (2) even once priced, the judge_plan's own
    token-count guess (800 in / 300 out) badly under-counted a VISION call
    (a rendered PNG embedded in the prompt), against a real, logged average
    of 2861 in / 585 out. Confirms the persisted preflight.json for the
    "frames" job now shows a realistic, non-trivial per-call cost for this
    label — not $0.0000, and not the old under-estimate either."""
    short_id = "stub_e2e_judgejson"
    _clean_reel_output(short_id)
    story = _load_story()
    shots = story_frames.select_sample(story_frames._scene_shots(story), 2)
    imagegen.reset_call_count(short_id)

    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        code = story_frames.run(short_id, shots, story, dry_run=False, yes=True,
                                include_cta=False)
    assert code == 0

    preflight_data = json.loads(
        (config.OUTPUT_DIR / short_id / "preflight.json").read_text(encoding="utf-8"))
    judge_model = next(m for m in preflight_data["frames"]["models"]
                       if m["label"] == "story_frame_judge")
    assert judge_model["cost_per_call"] > 0.001, (
        f"story_frame_judge's preflight cost_per_call is still near-zero: "
        f"{judge_model}")
    print(f"   ok — the persisted preflight.json now estimates a real, "
         f"non-trivial cost for story_frame_judge: "
         f"${judge_model['cost_per_call']:.4f}/call (was $0.0000)")


def test_run_sets_a_per_reel_budget_matching_the_formula():
    _clean_reel_output("stub_e2e_budgetcalc")
    story = _load_story()
    shots = story_frames.select_sample(story_frames._scene_shots(story), 3)
    imagegen.reset_call_count("stub_e2e_budgetcalc")

    assert not config.IMAGE_MAX_CALLS_PER_REEL_IS_EXPLICIT, (
        "this test assumes IMAGE_MAX_CALLS_PER_REEL was not set in the "
        "environment — the computed default is expected to apply")
    code = story_frames.run("stub_e2e_budgetcalc", shots, story, dry_run=False,
                            yes=True, include_cta=True)
    assert code == 0
    expected = config.default_image_budget(len(shots), config.STORY_FRAME_ATTEMPTS,
                                           has_mascot=True)
    assert imagegen._budget_for("stub_e2e_budgetcalc") == expected
    print(f"   ok — run() computes and sets the per-reel budget via "
         f"imagegen.set_reel_budget: {expected}")


def test_explicit_env_override_wins_over_the_computed_default():
    _clean_reel_output("stub_e2e_budgetoverride")
    story = _load_story()
    shots = story_frames.select_sample(story_frames._scene_shots(story), 3)
    imagegen.reset_call_count("stub_e2e_budgetoverride")

    original_explicit = config.IMAGE_MAX_CALLS_PER_REEL_IS_EXPLICIT
    original_flat = config.IMAGE_MAX_CALLS_PER_REEL
    config.IMAGE_MAX_CALLS_PER_REEL_IS_EXPLICIT = True
    config.IMAGE_MAX_CALLS_PER_REEL = 3   # deliberately far below the computed default
    try:
        try:
            story_frames.run("stub_e2e_budgetoverride", shots, story, dry_run=False,
                             yes=True, include_cta=True)
        except imagegen.ImageGenError:
            pass  # expected — budget=3 is deliberately too low to finish the run;
                  # hitting it mid-run is itself proof the override took effect
        # No set_reel_budget call happened, so imagegen falls back to the flat
        # (still-overridden-at-call-time) config value — 3, not the computed
        # one. Must be read BEFORE the finally block restores config below.
        observed_budget = imagegen._budget_for("stub_e2e_budgetoverride")
    finally:
        config.IMAGE_MAX_CALLS_PER_REEL_IS_EXPLICIT = original_explicit
        config.IMAGE_MAX_CALLS_PER_REEL = original_flat
    assert observed_budget == 3
    print("   ok — an explicit IMAGE_MAX_CALLS_PER_REEL always wins over "
          "the computed per-reel default")


# ==========================================================================
# STEP 6 — free pre-checks + judge + regenerate loop
# ==========================================================================

def _fresh_shot():
    story = _load_story()
    # A plain scene shot, not the reel's first `wide` one — the regenerate-
    # loop tests don't need the setting-reference machinery, just a shot to
    # generate against.
    return story_frames._scene_shots(story)[1], story


def _judge(character_match=5, no_text=5, action_visible=5, emotion_readable=5,
          style_match=5, setting_match=None, reasons=None) -> StoryFrameJudge:
    return StoryFrameJudge(character_match=character_match, no_text=no_text,
                           action_visible=action_visible, emotion_readable=emotion_readable,
                           style_match=style_match, setting_match=setting_match,
                           reasons=reasons or [])


def test_precheck_failure_never_spends_a_judge_call():
    """A frame that fails a free pre-check must be regenerated WITHOUT ever
    calling the judge — Part 1's whole reason for existing."""
    _clean_reel_output("stub_e2e_precheck")
    shot, story = _fresh_shot()
    judge_calls = []

    def fake_judge(*a, **kw):
        judge_calls.append(1)
        return _judge()

    original_size = frame_checks.check_size
    frame_checks.check_size = lambda img: frame_checks.PreCheckResult(
        "size", False, "forced failure for this test")
    original_judge = story_frames.judge_story_frame
    story_frames.judge_story_frame = fake_judge
    try:
        result = story_frames.render_shot_with_judge(
            "stub_e2e_precheck", shot, build_shot_prompt(shot, story),
            cast_refs_for_shot(shot), None, imagegen.StubImageProvider(), no_judge=False)
    finally:
        frame_checks.check_size = original_size
        story_frames.judge_story_frame = original_judge

    assert not judge_calls, "a pre-check failure must never reach the judge"
    assert result["final_status"] == "NEEDS_REVIEW"
    assert all(a["status"] == "PRECHECK_FAILED" for a in result["attempts"])
    print(f"   ok — every attempt failing check_size never calls the judge "
         f"({len(result['attempts'])} attempt(s), 0 judge calls), ends "
         f"NEEDS_REVIEW")


def test_judge_fail_then_pass_regenerates_with_fix_text_and_new_seed():
    """
    RESTYLE_TO_STORY_REELS.md Step 6 Part 3, verbatim: 'On fail: append the
    judge's reasons as "FIX: ..." to the prompt, use a new seed, regenerate.'
    A recording fake provider proves both halves of that sentence actually
    happened, not just that the shot eventually passed.
    """
    _clean_reel_output("stub_e2e_judge_regen")
    shot, story = _fresh_shot()

    class _RecordingStub(imagegen.StubImageProvider):
        name = "stub_judge_regen_record"   # own cache namespace — see Step 5's
                                           # test file note on why this matters
        def __init__(self):
            self.calls = []
        def generate(self, prompt, refs=None, size=imagegen.FRAME_SIZE, seed=None, shot_id=""):
            self.calls.append({"prompt": prompt, "seed": seed})
            return super().generate(prompt, refs=refs, size=size, seed=seed, shot_id=shot_id)

    provider = _RecordingStub()
    verdicts = [
        _judge(character_match=2, reasons=["hair color does not match the reference"]),
        _judge(),   # clean pass
    ]
    calls = {"n": 0}

    def fake_judge(*a, **kw):
        v = verdicts[calls["n"]]
        calls["n"] += 1
        return v

    original = story_frames.judge_story_frame
    story_frames.judge_story_frame = fake_judge
    try:
        result = story_frames.render_shot_with_judge(
            "stub_e2e_judge_regen", shot, build_shot_prompt(shot, story),
            cast_refs_for_shot(shot), None, provider, no_judge=False)
    finally:
        story_frames.judge_story_frame = original

    assert result["final_status"] == "PASS"
    assert len(result["attempts"]) == 2
    assert len(provider.calls) == 2
    assert provider.calls[0]["seed"] is None
    assert provider.calls[1]["seed"] == 2, provider.calls[1]["seed"]
    assert "FIX:" in provider.calls[1]["prompt"]
    assert "hair color does not match the reference" in provider.calls[1]["prompt"]
    print(f"   ok — a failing judge verdict regenerates with the reasons "
         f"appended as 'FIX: ...' and a new seed ({provider.calls[1]['seed']}), "
         f"then passes on attempt 2")


def test_exhausted_attempts_marks_needs_review_and_keeps_best_scoring():
    """
    Both attempts fail (STORY_FRAME_ATTEMPTS defaults to 2), with DIFFERENT
    judge totals — proves "keep the best attempt" means the higher-scoring
    one's actual pixels end up at final_path, not just whichever ran last.
    """
    _clean_reel_output("stub_e2e_exhaust")
    shot, story = _fresh_shot()

    class _RecordingStub(imagegen.StubImageProvider):
        name = "stub_exhaust_record"
        def __init__(self):
            self.frames = []
        def generate(self, prompt, refs=None, size=imagegen.FRAME_SIZE, seed=None, shot_id=""):
            raw = super().generate(prompt, refs=refs, size=size, seed=seed, shot_id=shot_id)
            self.frames.append(raw)
            return raw

    provider = _RecordingStub()
    # attempt 1 scores HIGHER (22) than attempt 2 (21) — both still fail
    # (character_match < 3 either way), so attempt 1 is the one that must
    # survive as final_path's actual content.
    verdicts = [
        _judge(character_match=2, reasons=["attempt 1: still a bit off"]),      # total 22
        _judge(character_match=1, reasons=["attempt 2: worse, not better"]),   # total 21
    ]
    calls = {"n": 0}

    def fake_judge(*a, **kw):
        v = verdicts[calls["n"]]
        calls["n"] += 1
        return v

    original = story_frames.judge_story_frame
    story_frames.judge_story_frame = fake_judge
    try:
        result = story_frames.render_shot_with_judge(
            "stub_e2e_exhaust", shot, build_shot_prompt(shot, story),
            cast_refs_for_shot(shot), None, provider, no_judge=False)
    finally:
        story_frames.judge_story_frame = original

    assert result["final_status"] == "NEEDS_REVIEW"
    assert len(result["attempts"]) == 2
    assert [a["status"] for a in result["attempts"]] == ["FAIL", "FAIL"]
    final_bytes = Path(result["final_path"]).read_bytes()
    assert final_bytes == provider.frames[0], (
        "final_path's actual pixels must be attempt 1's (higher total, 22), "
        "not attempt 2's (21) even though attempt 2 ran last and would "
        "otherwise be what's left on disk")
    print(f"   ok — both attempts fail -> NEEDS_REVIEW, and final_path's "
         f"actual bytes are the BEST-scoring attempt's (attempt 1, total 22), "
         f"not just the last one written")


def test_run_continues_to_next_shot_after_a_needs_review():
    """A shot marked NEEDS_REVIEW must not stop the reel — the caller (run())
    moves on to the next shot regardless."""
    _clean_reel_output("stub_e2e_continue")
    story = _load_story()
    shots = story_frames.select_sample(story_frames._scene_shots(story), 2)

    def always_fail_judge(*a, **kw):
        return _judge(character_match=1, reasons=["forced failure for this test"])

    original = story_frames.judge_story_frame
    story_frames.judge_story_frame = always_fail_judge
    try:
        code = story_frames.run("stub_e2e_continue", shots, story, dry_run=False,
                                yes=True, include_cta=False)
    finally:
        story_frames.judge_story_frame = original

    assert code == 0
    judge_data = story_frames._load_judge_data("stub_e2e_continue")
    assert len(judge_data) == len(shots)
    assert all(r["final_status"] == "NEEDS_REVIEW" for r in judge_data.values())
    print(f"   ok — every sampled shot scoring NEEDS_REVIEW still lets run() "
         f"process all {len(shots)} of them and finish cleanly (never "
         f"crashes, never stops early)")


def test_budget_cap_stops_regenerates():
    _clean_reel_output("stub_e2e_budget")
    shot, story = _fresh_shot()
    imagegen.reset_call_count("stub_e2e_budget")
    original_budget = config.IMAGE_MAX_CALLS_PER_REEL
    config.IMAGE_MAX_CALLS_PER_REEL = 1   # only the FIRST attempt is allowed through

    # OWN cache namespace, like Step 5's own test file note explains — this
    # test needs attempt 1 to be a guaranteed real (budget-consuming) call,
    # not a hit served from a previous test's identical prompt+seed=None.
    class _BudgetStub(imagegen.StubImageProvider):
        name = "stub_budget_test"

    def always_fail_judge(*a, **kw):
        return _judge(character_match=1, reasons=["forced failure"])

    original_judge = story_frames.judge_story_frame
    story_frames.judge_story_frame = always_fail_judge
    try:
        try:
            story_frames.render_shot_with_judge(
                "stub_e2e_budget", shot, build_shot_prompt(shot, story),
                cast_refs_for_shot(shot), None, _BudgetStub(),
                no_judge=False)
            assert False, "expected ImageGenError once the budget is exceeded"
        except ImageGenError as e:
            assert "IMAGE_MAX_CALLS_PER_REEL" in str(e)
    finally:
        story_frames.judge_story_frame = original_judge
        config.IMAGE_MAX_CALLS_PER_REEL = original_budget
    print(f"   ok — IMAGE_MAX_CALLS_PER_REEL stops a regenerate loop mid-way, "
         f"the same budget every real image call already respects")


def test_judge_json_shape_and_summary_printed():
    _dedicated_short_id("stub_e2e_judgejson")
    story = _load_story()
    shots = story_frames.select_sample(story_frames._scene_shots(story), 3)

    code, out = _run(["stub_e2e_judgejson", "--sample", "3", "--yes"])
    assert code == 0

    judge_path = story_frames._judge_path("stub_e2e_judgejson")
    assert judge_path.exists()
    data = json.loads(judge_path.read_text())
    for shot_id, record in data.items():
        assert set(record) == {"attempts", "final_status", "final_path"}
        assert record["final_status"] in ("PASS", "NEEDS_REVIEW")
        for a in record["attempts"]:
            assert set(a) >= {"attempt", "seed", "pre_checks", "judge", "status"}
            for pc in a["pre_checks"]:
                assert set(pc) == {"name", "passed", "reason", "skipped"}

    assert "summary" in out.lower()
    assert "passed:" in out
    assert "needs_review:" in out
    assert "total image calls:" in out
    assert "total judge calls:" in out
    assert "estimated cost:" in out.lower()
    print(f"   ok — judge.json has the documented shape for every shot, and "
         f"the summary (passed/needs_review/image calls/judge calls/cost) "
         f"is printed: {judge_path}")


def test_no_judge_skips_the_judge_entirely():
    _dedicated_short_id("stub_e2e_nojudge")
    calls = []

    def fake_judge(*a, **kw):
        calls.append(1)
        return _judge()

    original = story_frames.judge_story_frame
    story_frames.judge_story_frame = fake_judge
    try:
        code, out = _run(["stub_e2e_nojudge", "--sample", "3", "--yes", "--no-judge"])
    finally:
        story_frames.judge_story_frame = original

    assert code == 0
    assert not calls, "no-judge must never call the judge"
    data = json.loads(story_frames._judge_path("stub_e2e_nojudge").read_text())
    assert all(r["final_status"] == "PASS" for r in data.values())
    assert all(a["judge"] is None for r in data.values() for a in r["attempts"])
    print(f"   ok — --no-judge renders and pre-checks every shot but never "
         f"calls judge_story_frame ({len(data)} shot(s), 0 judge calls)")


def test_rejudge_updates_one_shot_without_a_new_image_call():
    _dedicated_short_id("stub_e2e_rejudge")
    _run(["stub_e2e_rejudge", "--sample", "1", "--yes", "--no-judge"])
    data_before = json.loads(story_frames._judge_path("stub_e2e_rejudge").read_text())
    shot_id = next(iter(data_before))

    image_calls = []
    original_generate = imagegen.StubImageProvider.generate
    imagegen.StubImageProvider.generate = lambda self, *a, **kw: (
        image_calls.append(1), original_generate(self, *a, **kw))[1]
    try:
        code = story_frames.main(["stub_e2e_rejudge", "--rejudge", shot_id])
    finally:
        imagegen.StubImageProvider.generate = original_generate

    assert code == 0
    assert not image_calls, "--rejudge must never generate a new image"
    data_after = json.loads(story_frames._judge_path("stub_e2e_rejudge").read_text())
    assert data_after[shot_id]["final_status"] == "PASS"
    assert len(data_after[shot_id]["attempts"]) == len(data_before[shot_id]["attempts"]) + 1
    assert data_after[shot_id]["attempts"][-1]["judge"] is not None
    print(f"   ok — --rejudge {shot_id} re-checks the existing frame (judge "
         f"now populated) without any new image call")


# ==================================================== STEP 8 Part 1 — reuse

def _shot(shot_id, characters, framing, emotion, key_prop=None,
         story_beat=None, camera="static", action="a", kind="scene"):
    return Shot(shot_id=shot_id, characters=characters, action=action, kind=kind,
               framing=framing, emotion=emotion, key_prop=key_prop,
               story_beat=story_beat, camera=camera)


def test_reveal_epoch_increments_only_after_a_reaction_beat_shot():
    shots = [
        _shot("a", ["Rahul"], "medium", "calm", story_beat="problem"),
        _shot("b", ["Rahul"], "medium", "calm", story_beat="reaction"),   # the reveal
        _shot("c", ["Rahul"], "medium", "calm", story_beat="payoff"),
    ]
    epochs = story_frames._reveal_epochs(shots)
    assert epochs == {"a": 0, "b": 0, "c": 1}, epochs
    print(f"   ok — the reveal shot itself stays epoch 0 (it IS the "
         f"before/after boundary); only shots strictly after it move to "
         f"epoch 1: {epochs}")


def test_reuse_key_ignores_camera_but_not_the_other_four_fields():
    a = _shot("a", ["Rahul"], "medium", "calm", key_prop="mug", camera="zoom_in")
    b = _shot("b", ["Rahul"], "medium", "calm", key_prop="mug", camera="push_left")
    assert story_frames._reuse_key(a, 0) == story_frames._reuse_key(b, 0)

    diff_characters = _shot("c", ["Riya"], "medium", "calm", key_prop="mug")
    diff_framing = _shot("d", ["Rahul"], "wide", "calm", key_prop="mug")
    diff_emotion = _shot("e", ["Rahul"], "medium", "frustrated", key_prop="mug")
    diff_prop = _shot("f", ["Rahul"], "medium", "calm", key_prop="ledger")
    for other in (diff_characters, diff_framing, diff_emotion, diff_prop):
        assert story_frames._reuse_key(a, 0) != story_frames._reuse_key(other, 0), other.shot_id
    print("   ok — the reuse key matches across a different camera move alone, "
         "and differs on any of characters/framing/emotion/key_prop")


def test_reuse_key_differs_across_a_reveal_even_with_identical_other_fields():
    shots = [
        _shot("before", ["Rahul"], "medium", "calm", key_prop="mug"),
        _shot("reveal", ["Rahul"], "medium", "surprised", story_beat="reaction"),
        _shot("after", ["Rahul"], "medium", "calm", key_prop="mug"),
    ]
    epochs = story_frames._reveal_epochs(shots)
    key_before = story_frames._reuse_key(shots[0], epochs["before"])
    key_after = story_frames._reuse_key(shots[2], epochs["after"])
    assert key_before != key_after, (key_before, key_after)
    print(f"   ok — 'before' and 'after' shots with IDENTICAL characters/"
         f"framing/emotion/key_prop still get different reuse keys because "
         f"a reveal sits between them: {key_before} != {key_after}")


def test_run_reuses_an_image_across_matching_shots_and_copies_the_same_bytes():
    _clean_reel_output("stub_e2e_reuse")
    story = _load_story()
    # Two shots engineered to share a reuse key (same characters/framing/
    # emotion/key_prop, different camera), inserted into a real story's shot
    # list so run()'s full pipeline (budget, judge, etc.) exercises them.
    base = next(s for s in story_frames._scene_shots(story) if s.story_beat != "reaction")
    twin = base.model_copy(update={
        "shot_id": f"{base.shot_id}_twin",
        "camera": "push_left" if base.camera != "push_left" else "push_right",
    })
    # Spliced in RIGHT AFTER `base`, not appended at the end — the epoch is
    # computed from story.shots' own chronological order (_reveal_epochs),
    # so a twin appended after this story's own later reveals would land in
    # a LATER epoch than `base` and correctly never reuse it; this test is
    # about same-epoch reuse, so it needs the two adjacent.
    idx = story.shots.index(base)
    story.shots = story.shots[:idx + 1] + [twin] + story.shots[idx + 1:]
    (config.OUTPUT_DIR / "stub_e2e_reuse.story.json").write_text(
        story.model_dump_json(indent=2), encoding="utf-8")

    code, out = _run(["stub_e2e_reuse", "--all", "--yes", "--no-judge"])
    assert code == 0, out
    assert f"REUSED from {base.shot_id}" in out, out
    data = json.loads(story_frames._judge_path("stub_e2e_reuse").read_text())
    assert data[twin.shot_id]["reused_from"] == base.shot_id

    base_bytes = (config.OUTPUT_DIR / "stub_e2e_reuse" / "frames" /
                 f"shot_{base.shot_id}.png").read_bytes()
    twin_bytes = (config.OUTPUT_DIR / "stub_e2e_reuse" / "frames" /
                 f"shot_{twin.shot_id}.png").read_bytes()
    assert base_bytes == twin_bytes, "a reused shot's file must be a byte-for-byte copy"
    print(f"   ok — a shot sharing {base.shot_id}'s characters/framing/"
         f"emotion/key_prop (different camera: {base.camera!r} vs "
         f"{twin.camera!r}) reuses its image — {twin.shot_id}'s own frame "
         f"file is a byte-for-byte copy, no provider call spent on it")


def test_story_image_reuse_env_flag_disables_reuse():
    _clean_reel_output("stub_e2e_reuse_off")
    story = _load_story()
    base = next(s for s in story_frames._scene_shots(story) if s.story_beat != "reaction")
    twin = base.model_copy(update={"shot_id": f"{base.shot_id}_twin2", "camera": "shake"})
    idx = story.shots.index(base)
    story.shots = story.shots[:idx + 1] + [twin] + story.shots[idx + 1:]
    (config.OUTPUT_DIR / "stub_e2e_reuse_off.story.json").write_text(
        story.model_dump_json(indent=2), encoding="utf-8")

    original = config.STORY_IMAGE_REUSE
    config.STORY_IMAGE_REUSE = False
    try:
        code, out = _run(["stub_e2e_reuse_off", "--all", "--yes", "--no-judge"])
    finally:
        config.STORY_IMAGE_REUSE = original

    assert code == 0, out
    assert "REUSED" not in out
    assert "STORY_IMAGE_REUSE=0 — disabled" in out
    print("   ok — STORY_IMAGE_REUSE=0 renders every shot independently, "
         "even two that would otherwise share a reuse key")


def main() -> int:
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    print(f"running {len(tests)} story_frames tests")
    for t in tests:
        print(f"- {t.__name__}")
        t()
    print("\nALL STORY_FRAMES TESTS PASSED.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
